name: example

dependencies:
  func_comp:
    path: ../../func_comp
  built_redux:
    path: ../.

dev_dependencies:
  browser: any
  built_collection: ^1.3.0
  build: ^0.7.0
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0
  test: "^0.12.6+2"

transformers:
  - built_redux
  - $dart2js

environment:
  sdk: ">=1.17.1 <2.0.0"
