name: example

dependencies:
  recompose_dart: '^0.0.9'
  react_built_redux:
    git:
      url: git://github.com/davidmarne/react_built_redux.git
      ref: master

dev_dependencies:
  browser: any
  built_collection: ^1.3.0
  build: ^0.7.0
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0
  test: "^0.12.6+2"

dependency_overrides:
  built_redux:
    path: ../.
  react:
    git:
      url: git://github.com/greglittlefield-wf/react-dart.git
      ref: context


transformers:
  - $dart2js

environment:
  sdk: ">=1.17.1 <2.0.0"
