builders:
  built_redux:
    target: ":built_redux"
    import: "package:built_redux/builder.dart"
    builder_factories: ["builtRedux"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    build_to: source