targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: false
      built_redux|built_redux:
        enabled: true

builders:
  built_redux:
    target: ":built_redux"
    import: "package:built_redux/builder.dart"
    builder_factories: ["builtRedux"]
    build_extensions: {".dart": ["g.dart"]}
    auto_apply: dependents
    build_to: source