builders:
  built_redux:
    target: ":built_redux"
    import: "package:built_redux/builder.dart"
    builder_factories: ["builtRedux"]
    build_extensions: {".dart": ["built_redux.g.dart"]}
    auto_apply: dependents
    build_to: source