name: built_redux
version: 9.0.0
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: ^4.6.0
  build: ^2.3.1
  built_collection: ^5.1.1
  built_value: ^8.4.1
  source_gen: ^1.2.5
  test: ^1.20.0

dev_dependencies:
  build_runner: ^2.2.1
  build_test:
  built_value_generator: ^8.4.1
  build_web_compilers: ^3.2.6
  workiva_analysis_options: ^1.2.2

environment:
  sdk: ">=2.17.0 <3.0.0"
