name: built_redux
version: 2.0.0
description:
  A state management library written in dart that enforces immutability
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: ">=0.26.1+3 <0.30.0"
  built_value: ^1.0.0
  source_gen: '>=0.5.0+03 <0.6.0'
  build: ^0.7.0

dev_dependencies:
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0
  dart_dev: "^1.0.0"
  dart_style: '>=0.2.4 <2.0.0'
  coverage: ^0.7.3
  test: "^0.12.0"

environment:
  sdk: ">=1.17.1 <2.0.0"
