name: built_redux
version: 7.4.4-dev
description:
  A state management library written in dart that enforces immutability
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=0.29.0 <0.33.0'
  build: ^0.12.0
  built_collection: '>=1.0.0 <4.0.0'
  built_value: ^5.2.0
  built_value_generator: ^5.2.0
  source_gen: '>=0.7.0 <0.9.0'
  test: '>=0.12.0 <2.0.0'

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

environment:
  sdk: '>=2-0-0-dev <2.0.0'