name: built_redux

dependencies:
  analyzer: ">=0.26.1+3 <0.30.0"
  barback: ^0.15.2
  built_value: ^1.0.0
  source_gen: '>=0.5.0+03 <0.6.0'
  transformer_utils: "^0.1.1"

dev_dependencies:
  built_collection: ^1.3.0
  build: ^0.7.0
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0
  test: "^0.12.6+2"

transformers:
  - $dart2js

environment:
  sdk: ">=1.17.1 <2.0.0"
